### PR TITLE
use eurec4a-intake requirements

### LINKED ISSUE #107: Issue with intake 3.x.x
The request of datasets that are accessed via intake currently fail with:

```
("missing 'module'", {'module': 'intake_xarray'})
```

This is an issue we already fixed for the eurec4a intake catalog CI by fixing the version of intake to `<3.0.0`

### PR DESCRIPTION
**Pull request by observingClouds**
- ensures up-to-date requirements for eurec4a-intake

fixes #107

### CODE REVIEW

**Comment by d70-t** [comment]
Ah, nice hack :-) I kind of like it.

I'm now just wondering if we might want to try going even more sustainable, and define all those requirements in the `eurec4a` python package? Maybe as an optional dependency like `eurec4a[data]` to emphasize that we want not only the dependencies which are required to execute the eurec4a package, but also those to access all the data? This would then also simplify end user installs.

**Comment by observingClouds** [comment]
Yeah, that sounds great. You wanna do this? ;P

**Comment by observingClouds** [comment]
@d70-t, I wanted to do this mostly quickly because I wanted to merge another PR to the book which should be visible online tomorrow...

**Comment by d70-t** [comment]
I'd be fine with merging this for now. But probably the `eurec4a` package approach doesn't take too long as well.

**Comment by observingClouds** [comment]
I'm a bit confused why I get here for the ICON-LES notebook the error 

```
File [0;32m/usr/share/miniconda3/envs/how_to_eurec4a/lib/python3.12/site-packages/dask/dataframe/__init__.py:24[0m, in [0;36m_dask_expr_enabled[0;34m()[0m
[1;32m     22[0m     [38;5;28;01mimport[39;00m [38;5;21;01mdask_expr[39;00m  [38;5;66;03m# noqa: F401[39;00m
[1;32m     23[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[0;32m---> 24[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mMust install dask-expr to activate query planning.[39m[38;5;124m"[39m)
[1;32m     25[0m [38;5;28;01mreturn[39;00m [38;5;28;01mTrue[39;00m

[0;31mValueError[0m: Must install dask-expr to activate query planning.
```

but the tests in eurec4a-intake work just fine without installing `intake[dataframe]` (which I just removed here now).

**Comment by d70-t** [comment]
Maybe we don't need `[dataframe]` anymore 🤷‍♂️

**Comment by d70-t** [comment]
Maybe this has something to do with the [latest release of dask](https://docs.dask.org/en/stable/changelog.html?highlight=2022#v2024-3-0). Apparently they made something based on `dask-expr` the default.

**Comment by observingClouds** [comment]
close in favour of #111

**Pull request closed without merging**
